# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm"  # or "pip" for Python
    directory: "/"            # Location of manifest (package.json or requirements.txt)
    schedule:
      interval: "daily"
